"""Download a curated set of free Google Fonts and bundle them LOCALLY.

Why this exists: the app is 100% local — nothing should phone home at runtime.
So instead of linking to fonts.googleapis.com (which would hit Google on every
page load and break offline use), we download the .woff2 files ONCE into
frontend/fonts/ and generate frontend/fonts.css with @font-face rules that point
at those local files. After running this once, the reader fonts work fully offline.

Re-run any time to refresh or add fonts:  python scripts/fetch_fonts.py
"""
from __future__ import annotations

import pathlib
import re

import httpx

ROOT = pathlib.Path(__file__).resolve().parent.parent
FONTS_DIR = ROOT / "frontend" / "fonts"
CSS_OUT = ROOT / "frontend" / "fonts.css"

# A Chrome UA so Google serves the small modern .woff2 files (not big .ttf).
UA = ("Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 "
      "(KHTML, like Gecko) Chrome/124.0 Safari/537.36")

# Curated for *reading a novel*: book serifs + a few clean sans + accessibility.
# (slug, Google family query, axis query)
FAMILIES = [
    ("literata",          "Literata",              "ital,wght@0,400;0,700;1,400"),
    ("lora",              "Lora",                  "ital,wght@0,400;0,700;1,400"),
    ("merriweather",      "Merriweather",          "ital,wght@0,400;0,700;1,400"),
    ("eb-garamond",       "EB+Garamond",           "ital,wght@0,400;0,700;1,400"),
    ("bitter",            "Bitter",                "ital,wght@0,400;0,700;1,400"),
    ("source-serif",      "Source+Serif+4",        "ital,wght@0,400;0,700;1,400"),
    ("pt-serif",          "PT+Serif",              "ital,wght@0,400;0,700;1,400"),
    ("libre-baskerville", "Libre+Baskerville",     "ital,wght@0,400;1,400"),
    ("crimson",           "Crimson+Pro",           "ital,wght@0,400;0,700;1,400"),
    ("vollkorn",          "Vollkorn",              "ital,wght@0,400;0,700;1,400"),
    ("spectral",          "Spectral",              "ital,wght@0,400;0,700;1,400"),
    ("alegreya",          "Alegreya",              "ital,wght@0,400;0,700;1,400"),
    ("noto-serif",        "Noto+Serif",            "ital,wght@0,400;0,700;1,400"),
    ("inter",             "Inter",                 "wght@400;700"),
    ("open-sans",         "Open+Sans",             "ital,wght@0,400;0,700;1,400"),
    ("atkinson",          "Atkinson+Hyperlegible", "ital,wght@0,400;0,700;1,400"),
    ("lexend",            "Lexend",                "wght@400;700"),
]

# Only keep these subsets (latin covers English novels; latin-ext adds accents).
KEEP_SUBSETS = {"latin", "latin-ext"}

BLOCK_RE = re.compile(r"/\*\s*([\w-]+)\s*\*/\s*(@font-face\s*\{.*?\})", re.S)
URL_RE = re.compile(r"url\((https://[^)]+?\.woff2)\)")


def main() -> None:
    FONTS_DIR.mkdir(parents=True, exist_ok=True)
    css_blocks: list[str] = [
        "/* Auto-generated by scripts/fetch_fonts.py — do not edit by hand.",
        "   Local copies of free Google Fonts so the reader works fully offline. */",
        "",
    ]
    total_files = 0
    with httpx.Client(headers={"User-Agent": UA}, timeout=60.0, follow_redirects=True) as client:
        for slug, query, axes in FAMILIES:
            url = f"https://fonts.googleapis.com/css2?family={query}:{axes}&display=swap"
            r = client.get(url)
            r.raise_for_status()
            kept = 0
            for subset, block in BLOCK_RE.findall(r.text):
                if subset not in KEEP_SUBSETS:
                    continue
                m = URL_RE.search(block)
                if not m:
                    continue
                font_url = m.group(1)
                # filename: slug + subset + a short hash of the url tail
                tail = font_url.rsplit("/", 1)[-1]
                fname = f"{slug}-{subset}-{tail}"
                fpath = FONTS_DIR / fname
                if not fpath.exists():
                    fr = client.get(font_url)
                    fr.raise_for_status()
                    fpath.write_bytes(fr.content)
                local_block = block.replace(font_url, f"fonts/{fname}")
                css_blocks.append(f"/* {query} {subset} */")
                css_blocks.append(local_block)
                css_blocks.append("")
                kept += 1
                total_files += 1
            print(f"  {slug:18} {kept} files")

    CSS_OUT.write_text("\n".join(css_blocks), encoding="utf-8")
    print(f"\nWrote {total_files} woff2 files to {FONTS_DIR}")
    print(f"Wrote {CSS_OUT}")


if __name__ == "__main__":
    main()
